### ISSUE TITLE
 error: no type named 'FloatType_t' in 'tempo::TSeries<double, std::__1::basic_string<char> >'

### ISSUE THREAD

**Issue by vivekmahato** [MonashTS/tempo#2]
While installing the project in python environment using the command:  python setup.py bdist_wheel
; the execution stops. 
The errors thrown are the following: 

../tempo/bindings/python/src/pytempo/tseries/bindings.hpp:14:31: error: no type named 'FloatType_t' in 'tempo::TSeries<double, std::__1::basic_string<char> >'

../tempo/bindings/python/src/pytempo/tseries/bindings.hpp:15:48: error: use of undeclared identifier 'ft'
        constexpr ssize_t scalar_size = sizeof(ft);
                                               ^
../tempo/bindings/python/src/pytempo/tseries/bindings.hpp:16:58: error: use of undeclared identifier 'ft'
        const std::string format = py::format_descriptor<ft>::format();  // Python struct-style format descriptor

**Comment by HerrmannM** [comment]
Thank you for the report. It should now be fixed.
Cheers!
