### ISSUE TITLE
Python Binding Installation Errors

### ISSUE THREAD

**Issue by yerbles** [MonashTS/tempo#3]
Hi,

I would like to incorporate these DTW speedup techniques in some clustering I am currently doing in python. I have come across some errors whilst following the install directions and thought to reach out for assistance.

I am using:
Python - 3.8.8
pip - 21.0.1
cmake - 3.22.1
wheel - 0.36.2

I pip installed "wheel" and downloaded the repo. I navigated to the bindings/python folder and ran "setup.py" which gave an error the first time as cmake was not installed. Then I pip installed "cmake" and reran the "python setup.py bdist_wheel" line which gave the error below. 

Any hints/tips/assistance you could provide would be greatly appreciated!
Thanks,
Luke

Command Window Output from running: "python setup.py bdist_wheel"
-------------------------------------------------------------------------------

running bdist_wheel
running build
running build_ext
build\temp.win-amd64-3.8\Release
['cmake', 'C:\\Users\\yer002\\Anaconda3\\tempo\\bindings\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\yer002\\Anaconda3\\tempo\\bindings\\python\\build\\lib.win-amd64-3.8\\', '-DPYTHON_EXECUTABLE=C:\\Users\\yer002\\Anaconda3\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\yer002\\Anaconda3\\tempo\\bindings\\python\\build\\lib.win-amd64-3.8\\', '-A', 'x64']
['cmake', '--build', '.', '--config', 'Release', '--', '/m']
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.14393.
-- pybind11 v2.6.1
CMake Warning (dev) at C:/Users/yer002/Anaconda3/Lib/site-packages/cmake/data/share/cmake-3.22/Modules/CMakeDependentOption.cmake:84 (message):
  Policy CMP0127 is not set: cmake_dependent_option() supports full Condition
  Syntax.  Run "cmake --help-policy CMP0127" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  lib/pybind11-2.6.1/CMakeLists.txt:91 (cmake_dependent_option)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Source directory: C:/Users/yer002/Anaconda3/tempo/bindings/python
-- Build directory:  C:/Users/yer002/Anaconda3/tempo/bindings/python/build/temp.win-amd64-3.8/Release
-- No build type selected, default to RelWithDebInfo
-- Reading version from include/tempo/utils/version.hpp
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/yer002/Anaconda3/tempo/bindings/python/build/temp.win-amd64-3.8/Release
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29913 for x64
  Copyright (C) Microsoft Corporation.  All rights reserved.
  cl /c /IC:\Users\yer002\Anaconda3\tempo\include /IC:\Users\yer002\Anaconda3\tempo\src /Wall /WX- /diagnostics:column
  /O2 /Ob2 /D _WINDLL /D _MBCS /D "VERSION_INFO=\"0.0.1\"" /D WIN32 /D _WINDOWS /D NDEBUG /D "CMAKE_INTDIR=\"Release\""
   /D tempo_EXPORTS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"tempo.dir\Rel
  ease\\" /Fd"tempo.dir\Release\vc142.pdb" /Gd /TP /errorReport:queue  -Wextra C:\Users\yer002\Anaconda3\tempo\src\temp
  o\reader\ts\ts.cpp
cl : command line error D8021: invalid numeric argument '/Wextra' [C:\Users\yer002\Anaconda3\tempo\bindings\python\buil
d\temp.win-amd64-3.8\Release\cpp\tempo.vcxproj]
Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    setup(
  File "C:\Users\yer002\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\yer002\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\yer002\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\yer002\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\yer002\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "C:\Users\yer002\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\yer002\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\yer002\Anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\yer002\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\yer002\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 73, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "C:\Users\yer002\Anaconda3\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.

**Comment by HerrmannM** [comment]
Hi!

Thanks for the report.
Unfortunately, I'm not familiar with windows ways... the log you posted says
`cl : command line error D8021: invalid numeric argument '/Wextra' [C:\Users\yer002\Anaconda3\tempo\bindings\python\buil
d\temp.win-amd64-3.8\Release\cpp\tempo.vcxproj]`
cl being the tool controlling MSVC. Clearly `/Wextra` is not numeric...

I just updated the build system for python, following pybind11 example (https://github.com/pybind/cmake_example).
Please try again the steps described in the readme and let me know what happens.

Otherwise, it should work on the linux subsystem (https://docs.microsoft.com/en-us/windows/wsl/)

Cheers,
Mat

**Comment by yerbles** [comment]
Thanks for getting back to me! I want to persevere with the pybind11/cmake option before looking into the linux subsystem option which seems daunting.
I did a bit more digging and it seems as though /Wextra isn't compatible with MSVC, and /W4 should be used instead. However I'm still getting errors with the jsonvalue.hpp file. The errors are:


 - Error C7555      use of designated initializers requires at least '/std:c++20'      \tempo\include\tempo\utils\jsonvalue.hpp      Lines 49, 52, 55, 58, 61...
 --------------------------
Either c++20 needs to included in the CMakeLists.txt file or the jsonvalue.hpp file syntax needs changing perhaps?


 - Error C2065	     'n': undeclared identifier	    \tempo\include\tempo\utils\jsonvalue.hpp	   Line 64	
 --------------------------
Could be related to the ss on line 63 in ssize_t?
 


This feels closer to resolution, but I'm a bit stuck at this point

**Comment by HerrmannM** [comment]
I updated the cmake file, it should now compile fine, let me know!

I'm still not confident that the setup.py is functional for windows...
If not, we can try to debug it together, or you should be able to directly used the compiled pybind module (a .so or .dll)

**Comment by yerbles** [comment]
Less or maybe just different errors. Just note there's a typo in the CMakeLists.txt file and it should have this


_if(MSVC)_
    add_compile_options(/W4)
else()
    add_compile_options(-Wall -Wextra)
endif()


Otherwise that part seems to be working fine now. 

------

There's still a handful of errors that are pointing at files in the src and include folders. Such as:
- tempo\include\tempo/tseries/dataset.hpp(185,18): error C2059: syntax error: 'template'
- tempo\include\tempo/utils/jsonvalue.hpp(63,15): error C2061: syntax error: identifier '
ssize_t'
- tempo\include\tempo/utils/jsonvalue.hpp(64,54): error C2065: 'n': undeclared identifier
- tempo\src\tempo\reader\ts\ts.cpp(202,34): warning C4244: 'argument': conversion from 'i
nt' to 'const _Elem', possible loss of data

-------

Traceback (most recent call last):
  File "C:\Users\yer002\Python\Packages\tempo\bindings\python\setup.py", line 123, in <module>
    setup(
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\yer002\Python\Packages\tempo\bindings\python\setup.py", line 116, in build_extension
    subprocess.check_call(
  File "C:\Users\yer002\Anaconda3\envs\DTW_tempo\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release']' returned non-zero exit status 1.

**Comment by HerrmannM** [comment]
Thanks for that, I fixed the typo

* I now rememberer that ssize_t is not standard, but POSIX. Changed it for a long, so that should fix it.
* The syntax error is weird - I somehow needed to put at a certain point in time while coding with g++... it seems that it is not needed anymore, so I removed the 'template' part of the call
* The warning should not be an issue - I still added an explicit cast

**Comment by yerbles** [comment]
Another fire

LINK : fatal error LNK1181: cannot open input file 'cpp\Release\tempo.lib' [C:\Users\yer002\Python\Packages\tempo\bindings\python\b
uild\temp.win-amd64-3.9\Release\pytempo.vcxproj]

**Comment by HerrmannM** [comment]
Progress, the compilation seems OK.
Now, I have no experience with MS tools so I'll need a bit more info.

For example, after compilation, this is my build directory, containing the libtempo.so, which is probably the equivalent to what your linker is trying to link against
![image](https://user-images.githubusercontent.com/2685294/151695136-65d85570-97c3-4ba4-bc63-5e99a4a85ded.png)

If you can show me what your build directory looks like at failure, and also copy/paste the full output of `python setup.py bdist_wheel`  (i.e, delete the generated directories and files, and relaunch the command), we may find a way to fix this!

**Comment by HerrmannM** [comment]
Updated to v0.0.2, which compiled on windows
Tested Using CLion and Visual Studio 2022 Community Edition Compiler 
* Architecture: x86_amd64
* Compiler ID: MSVC
* Compiler Version: 19.31.31107.0
